config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customer/sessions',
  passwords:     'customer/passwords',
  registrations: 'customer/registrations'
}

  #管理者
  namespace :admin do

    root to: 'tops#top'
    resources :order_products, only:[:update]

    resources :orders, only: [:index, :show, :update]

    resources :customers, only: [:show, :edit, :index, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :products, except: [:destroy]
  end

  #顧客
  scope module: :customer do
    get '/about', to: 'homes#about'

    resources :addresses, only: [:index, :create, :edit, :destroy]
    patch 'addresses/:id/update', to: 'addresses#update', as: 'addresses_update'

    get 'genres/:id/sort', to: 'products#sort', as: 'genres_sort'
    resources :products, only: [:index, :show]
    root 'products#top'

    delete 'cart_products/destroy_all', to: 'cart_products#destroy_all'
    resources :cart_products, only: [:index, :create, :destroy]
    patch 'cart_products/:id', to: 'cart_products#update'

    get 'orders/complete'
    post 'orders/confirm'
    resources :orders, only: [:index, :show, :new, :create,]

    get 'customers/profile_edit', to: 'customers#edit', as: 'customers_edit'
    get 'customers/destroy_page', to: 'customers#destroy_page'
    patch 'customers/leave', to: 'customers#leave', as: 'customers_leave'
    get 'customers/my_page', to: 'customers#my_page'
    patch 'customers/profile_update', to: 'customers#update', as: 'customers_update'
  end

  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :phone_number, presence: true, format: {with: /\A\d{10,11}\z/}
  validates :is_deleted, inclusion: {in: [true, false]}

  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def self.search(word)
    self.where(['last_name LIKE ? OR first_name LIKE ? OR last_name_kana LIKE ? OR first_name_kana LIKE ?', "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%"])
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      flash[:warning] = "入力内容を確認してください"
      render 'edit'
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :is_deleted)
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def new
    @product = Product.new
    @genre = Genre.where(is_active: true)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      @genre = Genre.where(is_active: true)
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @genre = Genre.where(is_active: true)
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @genre = Genre.where(is_active: true)
    if @product.update(product_params)
      redirect_to admin_product_path
    else
      render :edit
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :image, :introduction,
      :genre_id, :non_taxed_price, :is_active)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  before_action :authenticate_customer!
  
  def index
    @customer = current_customer
    @addresses = @customer.addresses
    @address = Address.new
    # @address_find = Address.find(params[:id])
  end

  def create
    @customer = current_customer
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path(@customer), notice: "You have created address successfully."
    else
      @addresses = @customer.addresses
      render 'index'
    end
  end

  def edit
    @address = Address.find(params[:id])
    @customer = current_customer
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to addresses_path, notice: "You have updated address successfully."
    else
      render :edit
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end
  
  private
  def address_params
    params.require(:address).permit(:postcode, :address, :name)
  end
  
end

app/controllers/customer/cart_products_controller.rb
class Customer::CartProductsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_products = CartProduct.where(customer_id: current_customer)
  end
  
  def create
    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.customer_id = current_customer.id
    @cart_product.save
    redirect_to cart_products_path
  end

  def update
    @cart_product = CartProduct.find(params[:id])
    @cart_product.update(cart_product_params)
    redirect_to cart_products_path
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_products_path
  end

  def destroy_all
    @cart_products = CartProduct.all
    @cart_products.destroy_all
    redirect_to cart_products_path
  end

  private
  def cart_product_params
    params.require(:cart_product).permit(:amount, :product_id)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
    
  def my_page
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
    unless current_customer.nil? || current_customer.id == @customer.id
      flash[:warning] = "アクセス権がありません"
      redirect_to edit_customer_path(current_customer)
    end
  end
  
  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_my_page_path, notice: "You have updated customer successfully."
    else
      render :edit
    end
  end
  
  def destroy_page
    @customer = current_customer
  end
  
  def is_deleted
  end
  
  def leave
    @customer = current_customer
    #is_deletedカラムにフラグを立てる(defaultはfalse)
    @customer.update(is_deleted: true)
    #ログアウトさせる
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number)
  end
  
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def about
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  #ログインユーザーのみ閲覧可
	before_action :authenticate_customer!

  #ログインユーザー(current_customer)の履歴一覧
  def index
    @orders = current_customer.orders
  end

  #履歴詳細
  def show
    @order = Order.find(params[:id])
    @order_product = @order.order_products
  end

  #注文情報入力
  def new
    @order = Order.new
  end

  #注文履歴の情報を作成
  def create
      @order = Order.new(order_params)
      @order.customer_id = current_customer.id
    if  @order.save!
      @carts = current_customer.cart_products
      #カートの中の情報をひとつづつ保存
      @carts.each do |cart|
        order_product = OrderProduct.new(order_id: @order.id)
        order_product.taxed_price = cart.product.non_taxed_price
        order_product.amount = cart.amount
        order_product.product_id = cart.product_id
        order_product.save!
      end
      #保存後カートの中を空にする
      @carts.destroy_all
      redirect_to orders_complete_path
    else
      @order = Order.new
      render :new
    end
  end

  #注文確認画面  if文で選択内容ごとの情報を
  def confirm
      #ログインユーザーのカートの中を全て表示
      @carts = current_customer.cart_products
      @order = Order.new
      @order.customer_id = current_customer.id
      @order.payment_method = params[:order][:payment_method]
      #自分の住所を選択した場合
    if "ご自身の住所" == params[:order][:current_customer]
      @order.name = current_customer.last_name
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address
      #登録済みの住所を選択した場合
    elsif "登録済み住所から選択" == params[:order][:current_customer]
      @address = Address.find(params[:order][:address_id])
      @order.name = @address.name
      @order.postcode = @address.postcode
      @order.address = @address.address
      #新しく住所を記述した場合
    elsif "新しいお届け先"  == params[:order][:current_customer]
      @address = Address.new
      @address.name = params[:order][:name]
      @address.postcode = params[:order][:postcode]
      @address.address = params[:order][:address]
      @address.customer_id = current_customer.id
      @address.save!
      @order.name = @address.name
      @order.postcode = @address.postcode
      @order.address = @address.address
    else
      @order = Order.new
      render :new
    end
  end

  #注文完了
  def complete
  end

  private
  def order_params
    params.require(:order).permit(:postcode,:address,:name,:payment_method,:status,:total_payment)
  end

end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def top
    rank_order_product_product_ids = OrderProduct.group(:product_id).order(amount: "DESC").limit(4).pluck(:product_id)
    @rank_products = Product.where(id: rank_order_product_product_ids).order_as_specified(id: rank_order_product_product_ids)
    @genres = Genre.where(is_active: true)
    @products = Product.all.page(params[:page]).per(4)
    # @product = Product.find(params[:id])
  end

  def index
    @products = Product.all.page(params[:page]).per(8)
    @genres = Genre.where(is_active: true)
  end

  def sort
    @genre = Genre.find(params[:id])
    @products = @genre.products.page(params[:page]).per(8)
    @genres = Genre.where(is_active: true)
    render :index
  end

  def show
    @product = Product.find(params[:id])
    @genres = Genre.where(is_active: true)
    @cart_product = CartProduct.new
  end

  # private
  # def product_params
  #   params.require(:product).permit(:name, :introduction, :genre_id, :image, :non_taxed_price, :is_active)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # protected
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  # end
  
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customer/products/_sidebar.html.erb
<table class="table table-hover table-bordered">
  <thead bgcolor='#dcdcdc'>
      <th>ジャンル検索</th>
  </thead>
  <tbody>
  <% genres.each do |genre| %>
    <tr>
      <td><%= link_to genres_sort_path(genre) do %><%= genre.name %><% end %></td>
    </tr>
  <% end %>
  </tbody>
 </table>

app/views/customer/products/index.html.erb
<div class="body">
  <div class="container-fluid">
    </br>
    <div class="row">
      <div class="col-xs-2" style="margin: 20px 0 50px 0">
        <%= render 'customer/products/sidebar', genres: @genres %>
      </div>
      <div class="col-xs-10">
          <h3><div class>商品一覧<span style="font-size:20px;">（全<%= @products.total_count %>件）</span></h3><br>
            <div class="row">
              <div class="col-xs-12 col-xs-offset-1">
      	      <% @products.each do |product| %>
                <div class="box" style="float:left; margin-right:120px;">
                  <%= link_to product_path(product) do %>
                    <%= attachment_image_tag product, :image, size:'200x150', fallback: "No_Image.jpg", size:'200x150' %><br>
                  <% end %>
                  <p><%= product.name %></p>
                  <p>¥<%= (product.non_taxed_price*1.1).floor.to_s(:delimited) %></p>
                  <% if product.is_active == false %>
                  <p class="product-is-active">売り切れ</p>
                  <% end %>
                </div>
              <% end %>
      	    </div>
            <div class="col-xs-6 col-xs-offset-4 ">
              <%= paginate @products %>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/customer/products/show.html.erb
<div class="body"> 
  <div class="container-fluid">
  	</br>
    <div class="row">
      <div class="col-xs-2" style="margin: 20px 0 50px 0">
        <%= render 'customer/products/sidebar', genres: @genres  %>
      </div>
      
      <div class="col-xs-10">
      	<div class="row">
				  <div style="float: left; margin: 0px 50px;">
						<%= attachment_image_tag @product, :image, size:'500x350', fallback: "No_Image.jpg", size:'500x350' %>
				  </div>
				  <div style="width:700px; height:500px; float:left;">
						<h2><%= @product.name %></h2><br>
						<p><%= @product.introduction %></p>
						<h3>¥<%= (@product.non_taxed_price*1.1).floor.to_s(:delimited) %><span style="font-size:12px;">（税込）</span></h3>
						<p><%= form_for (@cart_product) do |f| %>
				  			<%= f.hidden_field :product_id, :value => @product.id %>
				  			<% if customer_signed_in? %>
				        	<!--<= f.number_field :amount , placeholder: "個数選択", min: 1, max: 50 %>-->
				        	<%= f.select :amount, 個数選択:[1,2,3,4,5,6,7,8,9,10] %>
				        	<% if @product.is_active == false %>
							      <%= f.submit '売り切れ', class: "btn btn-new-register btn-lg", disabled: true %>
							    <% else %>
							      <%= f.submit "カートに入れる" ,class: 'btn btn-primary' %>
							    <% end %>
				        <% end %>
				       <% end %>
				    </p>
				  </div>
				</div>
	  	</div>
	  </div>
  </div>
</div>

app/views/customer/products/top.html.erb
<div class="body"> 
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-2" style="margin: 40px 0 50px 0">
        <%= render 'customer/products/sidebar', genres: @genres  %>
      </div>
      
      <div class="col-xs-10">
        <div class="top_background" style="margin: 80px 10px 100px 80px">
          <div class="top_text">
            <div>ようこそ、NaganoCakeへ！<br/>
                 このサイトは、ケーキ販売のECサイトになります。<br/>
                 会員でない方も商品の閲覧はできますが、<br/>
                 購入には会員登録が必要になります。
            </div>
        </div>
      </div>
      <!--IDが古い順に表示されるようにする？-->
          <h3>オススメ商品</h3>
              <% @rank_products.each do |rank_product| %>
                <div class="box" style="float:left; margin-right:120px;">
                  <%= link_to product_path(rank_product) do %>
                    <%= attachment_image_tag rank_product, :image, size:'200x150', fallback: "No_Image.jpg", size:'200x150' %><br>
                  <% end %>
                  <p><%= rank_product.name %></p>
                  <p>¥<%= (rank_product.non_taxed_price*1.1).floor.to_s(:delimited) %></p>
                  <% if rank_product.is_active == false %>
                  <p class="product-is-active">売り切れ</p>
                  <% end %>
                </div>
              <% end %>
            </div> 
          </div>
          
      <div class="row">
    	  <div class="col-xs-10"></div>
    	  <div class="col-xs-2">
    	    <p><%= link_to "もっと見る>", products_path %></p>
    	  </div>
      </div>
    </div>
  </div>
</div>