NaganoCAKE-develop/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customer/sessions',
  passwords:     'customer/passwords',
  registrations: 'customer/registrations'
}

  #管理者
  namespace :admin do
    patch 'order_products/:id', to: 'order_products#update'

    root to: 'top#top'

    resources :orders, only: [:index, :show]
    patch 'orders', to: 'orders#update'

    resources :customers, only: [:show, :edit, :index]
    patch 'customers', to: 'customers#update'

    resources :genres, only: [:index, :create, :edit]
    patch 'genres', to: 'genres#update'

    resources :products, except: [:destroy, :update]
    patch 'products/:id', to: 'products#update'
  end

  #顧客
  scope module: :customer do
    get '/about', to: 'homes#about'

    resources :addresses, only: [:index, :create, :edit, :destroy]
    patch 'addresses/:id', to: 'addresses#update'

    resources :products, only: [:index, :show]
    root 'products#top'

    resources :cart_products, only: [:index, :create, :destroy]
    delete :cart_products, to: 'cart_products#destroy_all'
    patch 'cart_products/:id', to: 'cart_products#update'

    get 'orders/complete'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm'

    get 'customers/my_page'
    resources :customers, only: [:edit]
    delete 'customers/destroy_page', to: 'customers#destroy_page'
    patch 'customers/leave', to: 'customers#leave'
    patch '/customers', to: 'customers#update'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

NaganoCAKE-develop/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :addresses, presence: true
  validates :phone_number, presence: true, format: {with: / \ A \ d {10,11} \ z /}
  validates :is_deleted, presence: true, inclusion: {in: [true, false]}
end

NaganoCAKE-develop/app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

NaganoCAKE-develop/app/controllers/admin/tops_controller.rb
class Admin::TopsController < ApplicationController
  def top
  end
end

NaganoCAKE-develop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

NaganoCAKE-develop/app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    # @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:id])
    if @order.save
       redirect_to confirm
    else
       @order = Order.new
       render new
    end
  end

  def confirm
  end

  def complete
  end

  private

  def order_params
    params.require(:order).permit(:pstcode,:address,:name,:payment_method,:status)
  end

end

NaganoCAKE-develop/app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

NaganoCAKE-develop/app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

NaganoCAKE-develop/app/helpers/application_helper.rb
module ApplicationHelper
end

NaganoCAKE-develop/app/views/admin/tops/top.html.erb
<h1>Tops#top</h1>
<p>Find me in app/views/tops/top.html.erb</p>

NaganoCAKE-develop/app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-contents">
  </div>
</footer>

NaganoCAKE-develop/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <h2>Logo</h2>
    </nav>

    <!--customer-->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if customer_signed_in? %>
          <li><%= link_to "マイページ", customers_my_page_path(current_user), class: "glyphicon glyphicon-home home" %></li>
          <li><%= link_to "商品一覧", products_path, class: "glyphicon glyphicon-gift" %></li>
          <li><%= link_to "カート", cart_products_path, class: "glyphicon glyphicon-shopping-cart"%></li>
          <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
        <% else %>
          <li><%= link_to "About", about_path, class: "glyphicon glyphicon-link about" %></li>
          <li><%= link_to "商品一覧", products_path, class: "glyphicon glyphicon-gift" %></li>
          <li><%= link_to "新規登録", new_customer_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to "ログイン", new_customer_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
        <% end %>
      </ul>
    </nav>

      <!--adomin-->
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <nav class='nav navbar-nav navbar-right' >
    		      <div class="col-sm-10">
    			      <input type="" class="" id="InputSearch" placeholder="Search">
    		      </div>
              </nav>
              <li><%= link_to "商品一覧",admin_orders_path, class: "glyphicon glyphicon-gift" %></li>
              <li><%= link_to "会員一覧",admin_customers_path, class: "glyphicon glyphicon-user"%></li>
              <li><%= link_to "注文履歴一覧",orders_path, class: "glyphicon glyphicon-list-alt"%></li>
              <li><%= link_to "ジャンル一覧",admin_genres_path, class: "glyphicon glyphicon-th-list" %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
            <% else %>
              <li><%= link_to "About",about_path, class: "glyphicon glyphicon-link about" %></li>
              <li><%= link_to "商品一覧",admin_products_path, class: "glyphicon glyphicon-gift" %></li>
              <li><%= link_to "新規登録",new_admin_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%= link_to "ログイン",new_admin_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
            <% end %>
          </ul>
        </nav>
  </div>
</header>

NaganoCAKE-develop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main>
      <div class="container">
      <p id="notice"><%= notice %></p>
    </main>
    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>