config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
}
  devise_for :customers, controllers: {
  sessions:      'customer/sessions',
  passwords:     'customer/passwords',
  registrations: 'customer/registrations'
}

  #管理者
  namespace :admin do

    root to: 'tops#top'
    resources :order_products, only:[:update]

    resources :orders, only: [:index, :show, :update]

    resources :customers, only: [:show, :edit, :index, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :products, except: [:destroy]
  end

  #顧客
  scope module: :customer do
    get '/about', to: 'homes#about'

    resources :addresses, only: [:index, :create, :edit, :destroy]
    patch 'addresses/:id/update', to: 'addresses#update', as: 'addresses_update'

    get 'genres/:id/sort', to: 'products#sort', as: 'genres_sort'
    resources :products, only: [:index, :show]
    root 'products#top'

    delete 'cart_products/destroy_all', to: 'cart_products#destroy_all'
    resources :cart_products, only: [:index, :create, :destroy]
    patch 'cart_products/:id', to: 'cart_products#update'

    get 'orders/complete'
    post 'orders/confirm'
    resources :orders, only: [:index, :show, :new, :create,]

    get 'customers/profile_edit', to: 'customers#edit', as: 'customers_edit'
    get 'customers/destroy_page', to: 'customers#destroy_page'
    patch 'customers/leave', to: 'customers#leave', as: 'customers_leave'
    get 'customers/my_page', to: 'customers#my_page'
    patch 'customers/profile_update', to: 'customers#update', as: 'customers_update'
  end

  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :name, presence: true

  def address_send
    name + "  " + postcode + "  " + address
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
  validates :amount, numericality: { only_integer: true }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :phone_number, presence: true, format: {with: /\A\d{10,11}\z/}
  validates :is_deleted, inclusion: {in: [true, false]}

  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def self.search(word)
    self.where(['last_name LIKE ? OR first_name LIKE ? OR last_name_kana LIKE ? OR first_name_kana LIKE ?', "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%"])
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  
  validates :name, presence: true
  validates :is_active,  inclusion: {in: [true, false]}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_products, dependent: :destroy

  validates :postcode, presence: true, format: {with: /\A\d{7}\z/}
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: {クレジットカード:0 ,銀行振込:1}
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備:3, 発送済:4}

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  # validates :taxed_price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true
  

  enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3} 
end

app/models/product.rb
class Product < ApplicationRecord
  extend OrderAsSpecified
  has_many :cart_products

  has_many :order_products

  belongs_to :genre
  attachment :image
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :non_taxed_price, numericality: { only_integer: true }

  def self.search(word)
    Product.where(['name LIKE ?', "%#{word}%"])
  end
end

app/controllers/admin/tops_controller.rb
class Admin::TopsController < ApplicationController
  def top
    now = Time.current
    @orders = Order.where(created_at: now.all_day)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :customer
      root_path
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
    @range = params[:range]
    word = params[:word]
    if @range == '1'
      @customers = Customer.search(params[:word])
    else
      @products = Product.search(params[:word]).page(params[:page]).per(10)
    end
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/searches/search.html.erb
<% if @range == '2'%>
<div class="body">
  <div class="container">
    <br></br>
    <h1>商品一覧</h1>
    <br></br>
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
      <%= link_to new_admin_product_path, data: {"turbolinks" => false}, class: "btn btn-info pull-right" do %>
      <i class="fas fa-plus"></i>
      <% end %>
      <br></br>
        <table class="table table-bordered">
          <thead bgcolor="#dcdcdc">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
    		  <% @products.each do |product| %>
      		  <tr>
              <td class="info col-xs-1">
                <%= product.id %>
              </td>
              <td class="text-left">
                <%= link_to admin_product_path(product), class: "btn-link" do %>
                <%= product.name %>
                <% end %>
              </td>
              <td class="text-right col-xs-1">
                <%= product.non_taxed_price.to_s(:delimited) %>
              </td>
              <td class="text-left col-xs-3">
                <%= product.genre.name %>
              </td>
              <td class="col-xs-2">
                <% if product.is_active == true %>
          			  <p>販売中</p>
          			<% elsif product.is_active == false %>
          				<p>販売停止中</p>
          			<% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <div class="text-center"><%= paginate @products %></div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 center-block" style="margin: 20px 0 50px 0">
      <h3 class='col-lg-10'>会員一覧</h3>
    </div>
    <div class="col-lg-12 center-block">
      <table class='table table-hover table-inverse'>
        <thead>
          <tr bgcolor="#dcdcdc">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to admin_customer_path(customer) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == false %>
                  <span class="panel panel-default">有効</span>
                <% else %>
                  <span class="panel panel-default">退会済み</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>